version: '3'
services:
  bank-api:
    container_name: bank-api
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./bank-api:/bank-api
    restart: on-failure
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes: 
      -  ./data:/app/data
   
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      -  ./data:/app/data

    
    
    