version: '3'
services:
  bank-api:
    container_name: bank-api
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./bank-api:/bank-api
    restart: on-failure
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes: 
      -  ./data:/app/data
    # command: >  
    #   bash -c "sleep 5 && go run /app/data/import_data.go"
   

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      -  ./data:/app/data
    # command: sh -c "mongoimport --db api_bank --collection OperationType --type json --file /app/data/operation_type.json --jsonArray"
    # "sleep 10 && chmod +x /app/data/import_data.sh && sh /app/data/import_data.sh"
    
    
    