// Code generated by MockGen. DO NOT EDIT.
// Source: ./transaction/controller.go

// Package mock_transaction is a generated GoMock package.
package mock_transaction

import (
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockITransactionController is a mock of ITransactionController interface
type MockITransactionController struct {
	ctrl     *gomock.Controller
	recorder *MockITransactionControllerMockRecorder
}

// MockITransactionControllerMockRecorder is the mock recorder for MockITransactionController
type MockITransactionControllerMockRecorder struct {
	mock *MockITransactionController
}

// NewMockITransactionController creates a new mock instance
func NewMockITransactionController(ctrl *gomock.Controller) *MockITransactionController {
	mock := &MockITransactionController{ctrl: ctrl}
	mock.recorder = &MockITransactionControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockITransactionController) EXPECT() *MockITransactionControllerMockRecorder {
	return m.recorder
}

// NewTransaction mocks base method
func (m *MockITransactionController) NewTransaction(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NewTransaction", c)
}

// NewTransaction indicates an expected call of NewTransaction
func (mr *MockITransactionControllerMockRecorder) NewTransaction(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTransaction", reflect.TypeOf((*MockITransactionController)(nil).NewTransaction), c)
}

// NewOperationType mocks base method
func (m *MockITransactionController) NewOperationType(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NewOperationType", c)
}

// NewOperationType indicates an expected call of NewOperationType
func (mr *MockITransactionControllerMockRecorder) NewOperationType(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewOperationType", reflect.TypeOf((*MockITransactionController)(nil).NewOperationType), c)
}
