// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_account is a generated GoMock package.
package mock_account

import (
	account "bank-api/account"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIAccountService is a mock of IAccountService interface
type MockIAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountServiceMockRecorder
}

// MockIAccountServiceMockRecorder is the mock recorder for MockIAccountService
type MockIAccountServiceMockRecorder struct {
	mock *MockIAccountService
}

// NewMockIAccountService creates a new mock instance
func NewMockIAccountService(ctrl *gomock.Controller) *MockIAccountService {
	mock := &MockIAccountService{ctrl: ctrl}
	mock.recorder = &MockIAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAccountService) EXPECT() *MockIAccountServiceMockRecorder {
	return m.recorder
}

// NewAccount mocks base method
func (m *MockIAccountService) NewAccount(newAccount account.Account) (*account.Account, []error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAccount", newAccount)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].([]error)
	return ret0, ret1
}

// NewAccount indicates an expected call of NewAccount
func (mr *MockIAccountServiceMockRecorder) NewAccount(newAccount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAccount", reflect.TypeOf((*MockIAccountService)(nil).NewAccount), newAccount)
}

// FindByID mocks base method
func (m *MockIAccountService) FindByID(id string) (*account.Account, []error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].([]error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID
func (mr *MockIAccountServiceMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIAccountService)(nil).FindByID), id)
}
